{
 "title": "Minimal Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(node_cpu_seconds_total, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total active CPU %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by(instance) (\r\n  sum without(cpu, mode) (\r\n    irate(node_cpu_seconds_total{mode!=\"idle\"}[1m])\r\n  )\r\n)\r\n",
     "legendFormat": "Total CPU usage"
    }
   ]
  },
  {
   "title": "User Mode CPU Usage (Per Core)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{mode=\"user\"}[5m])\r\n",
     "legendFormat": "core {{cpu}}"
    }
   ]
  },
  {
   "title": "Avg Active CPU Usage (Excl. Idle)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 9 },
   "targets": [
    {
     "expr": "avg without(cpu) (\r\n  irate(node_cpu_seconds_total{job=\"node\",instance=~\"$instance\", mode!=\"idle\"}[1m])\r\n)\r\n\r\n\r\n",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  { "title": "RAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node\",instance=~\"$instance\"} - node_memory_MemFree_bytes{job=\"node\",instance=~\"$instance\"} - node_memory_Cached_bytes{job=\"node\",instance=~\"$instance\"} - node_memory_Buffers_bytes{job=\"node\",instance=~\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"$instance\",job=\"node\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$instance\",job=\"node\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$instance\",job=\"node\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Total RAM Used (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100\r\n",
     "legendFormat": "VM de IP {{instance}}"
    }
   ]
  },
  { "title": "DISK SPACE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Available Disk Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{job=\"node\",instance=~\"$instance\",device!~\"/dev/loop.*\",device!~\"tmpfs|nsfs\",device!=\"gvfsd-fuse\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Filesystem Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "100 * (\r\n  node_filesystem_size_bytes{fstype!~\"tmpfs|devtmpfs\"}\r\n  - node_filesystem_free_bytes{fstype!~\"tmpfs|devtmpfs\"}\r\n)\r\n\r\n",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 36 },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"node\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{device}} receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"node\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{device}} transmit"
    }
   ]
  }
 ]
}